Meetup2/Controllers/MeetupGroupController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Meetup2.Extentions_Custom;
using Meetup2.Models;
using Meetup2.ViewModel;
using Microsoft.AspNet.Identity;

namespace Meetup2.Controllers
{
    [Authorize]
    public class MeetupGroupController : Controller
    {
        private ApplicationDbContext _context;

        public MeetupGroupController()
        {
            _context = new ApplicationDbContext();
        }

        // GET: MeetupGroup
        public ActionResult Index()
        {
            var currentUser = User.Identity.GetUserId();
            var groupInfo = _context.MeetUpGroups
                .Include(u=>u.Organizer)
                .Where(u => u.OrganizerId == currentUser)
                .ToList();
            
            if (!groupInfo.Any())
            {
               
                return RedirectToAction("New");
            }
           
            
            return View(groupInfo);
        }

        [AllowAnonymous]
        public ActionResult Show(int? id)
        {
            if (id == null) return Redirect("~");

            var currentUser = User.Identity.GetUserId();

            var meetupgroup = _context.MeetUpGroups
                .Include(m=>m.Organizer)
                .Single(m => m.Id == id);
                
            var meetups = _context.MeetUps
                .Where(m => m.MeetUpGroupId == id)
                .OrderBy(m => m.DateTime)
                .ToList();


            ViewBag.heading = meetupgroup.Title;

            var viewModel = new GroupViewModel()
            {
                Id = meetupgroup.Id,
                Title = meetupgroup.Title,
                Description = meetupgroup.Description,
                MeetUp = meetups,
                ShowButton = (currentUser== meetupgroup.Organizer.Id)?true:false


            };

            return View(viewModel);
        }
        public ActionResult New()
        {
            ViewBag.heading = "Start a new Meetup";
            return View();
        }

    
        public ActionResult Create(GroupViewModel viewModel)
        {
            var currentUser = User.Identity.GetUserId();
            var group = new MeetUpGroup()
            {
                Title = viewModel.Title,
                HomeTown = viewModel.HomeTown,
                Description = viewModel.Description,
                OrganizerId = currentUser
            };

            _context.MeetUpGroups.Add(group);
           // _context.SaveChanges();

            return RedirectToAction("Index");

        }
    }
}

Meetup2/Views/Shared/Footer.cshtml
<div class="row">
    <div class="col-md-12">
        <div class="secondary-footer">
            <ul>
                <li> <a rel="nofollow" href="#"> AofT-M&copy; 2017. All rights reserved.</a> </li>
                <li> <a rel="nofollow" href="#">Terms &amp; conditions</a> </li>
                <li> <a rel="nofollow" href="#">Privacy policy</a> </li>
                <li> <a href="#">Contact</a> </li>
            </ul>
        </div>
    </div>
</div>

Meetup2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" ng-app="MeetUp">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>@ViewBag.Title - Meetup Application - AofT-M</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular.min.js"></script>

    <!--[if lt IE 9]>
    <script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js'></script>
    <![endif]-->
    <!--[if lt IE 9]>
    <script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js'></script>
    <![endif]-->

    <meta name="description" content="Meetup -Sample Application">
    <meta name="author" content="MTofa">

 

</head>
<body>



    <div >

        <div class="row">

            <div class="col-md-5">
                <div class="topleftnav">

                    @Html.ActionLink("Create a Meetup Group", "New", "MeetupGroup")
                </div>

            </div>
            <div class="col-md-2 text-center">
              
                <a  href="/#/">
                    <img src='@Url.Content("~/content/Images/logo.png")'>
                </a>
            </div>

            <div class="col-md-3">


                @Html.Partial("_LoginPartial")


            </div>
            <div class="col-md-1"></div>
        </div>


        @Html.Partial("_SearchHeaderPartial")
        <div class="row">

            <div class="col-md-2"></div>
            <div class="col-md-8">

                @RenderBody()
            </div>

        </div>

        <!--detail container -->
        <!--Main container ends -->
    </div>




    @Html.Partial("Footer")





@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

  
   <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular-sanitize.min.js"></script>

    @Scripts.Render("~/bundles/angularProjectpkg")
    @Scripts.Render("~/bundles/angularProject")

    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-91623104-1', 'auto');  //main
  //ga('create', 'UA-92772688-1', 'auto');
  ga('send', 'pageview');

    </script>


@RenderSection("scripts", required: false)
</body>
</html>

Meetup2/Views/Shared/_RightMenuPartial.cshtml
@if (string.IsNullOrEmpty(ViewBag.RightMenu))
{

    
    

}

Meetup2/Views/Shared/_SearchHeaderPartial.cshtml
    <div class="parent-div">


        <div class="row jumbotron ">
          
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    <div class="container">
                        @if (string.IsNullOrEmpty(ViewBag.heading))
                        {
                            <h2 class="text-center">What do you love?</h2>
                            <p class="text-center">Do more of it with Meetup</p>
                        }
                        <br/>
                        <p class="text-center">@ViewBag.heading</p>



</div>
                </div>
          
        </div>


        <div ui-view="searchview"></div>
      

       


        <div>

        </div>


    </div>