Meetup2/Models/MeetUpGroup.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Web;

namespace Meetup2.Models
{
    public class MeetUpGroup
    {
        public  int Id { get; set; }
        public  string Title { get; set; }
        public  string Description { get; set; }
        public  ICollection<MeetUpGroupType> MeetUpGroupTypeses { get; set; }
        public  ApplicationUser Organizer { get; set; }
        public  string OrganizerId { get; set; }
        public  ICollection<MeetUp> MeetUps { get; set; }
        public  string HomeTown { get; set; }
        public  string MeetupGroupImage { get; set; }
        //ROT - Always initialize Collection. 
        public  MeetUpGroup()
        {
            MeetUpGroupTypeses = new Collection<MeetUpGroupType>();
            MeetUps = new Collection<MeetUp>();
        }
    }
}

Meetup2/Models/MeetUpGroupTypes.cs
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace Meetup2.Models
{
    public class MeetUpGroupType
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public ICollection<MeetUpGroup> MeetUpGroups { get; set; }

        public MeetUpGroupType()
        {
            MeetUpGroups = new Collection<MeetUpGroup>();
        }
    }
}

Meetup2/Controllers/MeetUpController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Meetup2.Models;
using Meetup2.Persistence;
using Meetup2.Repositories;
using Meetup2.ViewModel;
using Microsoft.AspNet.Identity;

namespace Meetup2.Controllers
{
    [Authorize]
    public class MeetUpController : Controller
    {
     
        //private ApplicationDbContext _context;
        private IUnitOfWork _unitOfWork;
    
        public MeetUpController(IUnitOfWork unitOfWork)
        {
            //_context= new ApplicationDbContext();
            //_unitOfWork =new UnitOfWork(new ApplicationDbContext());
            _unitOfWork= unitOfWork;
        }

        public ActionResult Index()
        {
            var currentUser = User.Identity.GetUserId();
            var eventLists = _unitOfWork
                             .MeetupGroupRepository.GetMeetupGroups(currentUser);

            /*
             *  Conditional Include
             *  By default, you cannnot select inside include.
             *  wrong - add "using System.Data.Entity;" and 
             *  Include inside select will work.
             *  Example - meetup group controller.
             *  Evernote - conditional include
             */
            //var dbQuery = from MeetUpGroup in _context.MeetUpGroups
            //              where MeetUpGroup.OrganizerId == currentUser
            //              select new
            //              {
            //                  MeetUpGroup,
            //                  Events = from MeetUp in MeetUpGroup.MeetUps
            //                           where MeetUp.IsCancled == false
            //                           select MeetUp

            //              };
            //var eventLists = dbQuery.AsEnumerable().Select(g => g.MeetUpGroup);
            var viewModel = new EventIndexViewModel()
            {
                MeetUpGroups = eventLists
            };

            return View(viewModel);
        }
        
        public ActionResult New(int id)
        {
            var currentUser = User.Identity.GetUserId();
            var groupInfo = _unitOfWork.MeetupGroupRepository
                .GetCurrentUsersMeetupGroupById(currentUser,id);

            if (groupInfo == null)
                return  RedirectToAction("new", "MeetupGroup");
   
         
            var viewModel = new EventViewModel()
            {
               MeetUpGroupId = id,
               DispalyTitle = groupInfo.Title

            };
            ViewBag.heading = groupInfo.Title;
            return View("EventForm", viewModel);
        }


        [ValidateAntiForgeryToken]
        public ActionResult Create(EventViewModel eventViewModel)
        {
            var currentUser = User.Identity.GetUserId();

            if (!ModelState.IsValid)
            {
                ViewBag.heading = eventViewModel.DispalyTitle;
                return View("EventForm", eventViewModel);
            }


            var eventinfo = new MeetUp()
            {
                Title = eventViewModel.Title,
                Location = eventViewModel.Location,
                Details = eventViewModel.Details,
                DateTime = eventViewModel.EventDate(),
                MeetUpGroupId = eventViewModel.MeetUpGroupId
            };

            
            _unitOfWork.MeetupRepository.Add(eventinfo);
            _unitOfWork.Complete();

            return RedirectToAction("Show", "MeetupGroup",new {id= eventViewModel.MeetUpGroupId});
        }

        public ActionResult Edit(int id)
        {

            //var currentUser = User.Identity.GetUserId();
            //var meetupLists = _context.MeetUpGroups
            //    .Where(m => m.OrganizerId == currentUser)
            //    .ToList();
            var eventInfo = _unitOfWork.MeetupRepository.GetMeetupById(id);

            if (eventInfo == null)
                return null;

            var viewModel = new EventViewModel()
            {
                MeetupId = eventInfo.Id,
                Title = eventInfo.Title,
                Location = eventInfo.Location,
                Details = eventInfo.Details,
                EventDateTime = eventInfo.DateTime.ToString("dd MMMM yyyy - hh:mm tt")
          
            };

            return View("EventForm", viewModel);



        }


        [ValidateAntiForgeryToken]
        public ActionResult Update(EventViewModel eventViewModel)
        {
            var currentUser = User.Identity.GetUserId();



            if (!ModelState.IsValid)
            {

                return View("EventForm", eventViewModel);
            }

            var eventInfo = _unitOfWork.MeetupRepository
                .GetSubscribersByMeetupId(eventViewModel.MeetupId);

            /*
             * It only creates row in notification table if there are subscribers.
             * 
             */
            eventInfo.UpdateAllSubscribers(eventViewModel);


            _unitOfWork.Complete();

            return RedirectToAction("Show", "MeetUpGroup",new {id=eventInfo.MeetUpGroupId});
        }

        
       
        [AllowAnonymous]
        public ActionResult Show(int id)
        {
            //if (id == null)
            //{
            //    return Redirect("~");
            //}
               
            var currentUserId = User.Identity.GetUserId();
            var eventInfo = _unitOfWork.MeetupRepository.GetMeetupById(id);

            var attandanceInfo = _unitOfWork.AttandanceRepository.GetAttendancesById(currentUserId).ToList()
                .ToLookup(a=>a.MeetUpId);

            var viewModel = new EventShowViewModel()
            {
                MeetUp = eventInfo,
                AttandanceLookup = attandanceInfo
            };


            ViewBag.RightLayoutVar = "show";
            ViewBag.heading = eventInfo.MeetUpGroup.Title;
            return View(viewModel);


        }

        [AllowAnonymous]
        public ActionResult RSVP()
        {
            var previousUrl = Request.UrlReferrer.AbsolutePath;

            return  new RedirectToRouteResult(
                new System.Web.Routing.RouteValueDictionary
                    {
                            { "controller", "Account" },
                            { "action", "Login" },
                            { "returnUrl", previousUrl }
                    });
        
        }
    }


}

Meetup2/Controllers/MeetupGroupController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Meetup2.Extentions_Custom;
using Meetup2.Models;
using Meetup2.ViewModel;
using Microsoft.AspNet.Identity;

namespace Meetup2.Controllers
{
    [Authorize]
    public class MeetupGroupController : Controller
    {
        private ApplicationDbContext _context;

        public MeetupGroupController()
        {
            _context = new ApplicationDbContext();
        }

        // GET: MeetupGroup
        public ActionResult Index()
        {
            var currentUser = User.Identity.GetUserId();
            var groupInfo = _context.MeetUpGroups
                .Include(u=>u.Organizer)
                .Where(u => u.OrganizerId == currentUser)
                .ToList();
            
            if (!groupInfo.Any())
            {
               
                return RedirectToAction("New");
            }
           
            
            return View(groupInfo);
        }

        [AllowAnonymous]
        public ActionResult Show(int? id)
        {
            if (id == null) return Redirect("~");

            var currentUser = User.Identity.GetUserId();

            var meetupgroup = _context.MeetUpGroups
                .Include(m=>m.Organizer)
                .Single(m => m.Id == id);
                
            var meetups = _context.MeetUps
                .Where(m => m.MeetUpGroupId == id)
                .OrderBy(m => m.DateTime)
                .ToList();


            ViewBag.heading = meetupgroup.Title;

            var viewModel = new GroupViewModel()
            {
                Id = meetupgroup.Id,
                Title = meetupgroup.Title,
                Description = meetupgroup.Description,
                MeetUp = meetups,
                ShowButton = (currentUser== meetupgroup.Organizer.Id)?true:false


            };

            return View(viewModel);
        }
        public ActionResult New()
        {
            ViewBag.heading = "Start a new Meetup";
            return View();
        }

    
        public ActionResult Create(GroupViewModel viewModel)
        {
            var currentUser = User.Identity.GetUserId();
            var group = new MeetUpGroup()
            {
                Title = viewModel.Title,
                HomeTown = viewModel.HomeTown,
                Description = viewModel.Description,
                OrganizerId = currentUser
            };

            _context.MeetUpGroups.Add(group);
           // _context.SaveChanges();

            return RedirectToAction("Index");

        }
    }
}

Meetup2/Views/MeetupGroup/Index.cshtml
@model IEnumerable<Meetup2.Models.MeetUpGroup>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Meetup Groups</h2>

    <div class="list-group">

        @foreach (var g in Model)
        {

           
                @Html.ActionLink(@g.Title, "Show", "MeetupGroup", new { id = g.Id },new {@class= "list-group-item" })

            <br/>


        }
    </div>

Meetup2/Views/MeetupGroup/New.cshtml
@model Meetup2.ViewModel.GroupViewModel
@{
    ViewBag.Title = "CreateGroup";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@Html.ValidationSummary()

<div class="col-sm-10">
   
    <br/>
    @using (Html.BeginForm("Create", "MeetupGroup"))
    {
        <div class="form-group">
            @Html.LabelFor(e => e.HomeTown, "What's your new Meetup Group's hometown?")
            @Html.TextBoxFor(e => e.HomeTown, new {@class = "form-control"})
            @Html.ValidationMessageFor(e => e.HomeTown)
        </div>

        <div class="form-group">
            @Html.LabelFor(e => e.Title, "What will your Meetup's name be?")
            @Html.TextBoxFor(e => e.Title, new {@class = "form-control"})
            @Html.ValidationMessageFor(e => e.Title)
        </div>


        <div class="form-group">
            @Html.LabelFor(e => e.Description, "Describe who should join, and what your Meetup will do.")
            @Html.TextAreaFor(e => e.Description, new {@class = "form-control"})
            @Html.ValidationMessageFor(e => e.Description)
        </div>




        @Html.AntiForgeryToken()
        <button type="submit" class="btn btn-primary"> Save </button>
    }

</div>

Meetup2/Views/MeetupGroup/Show.cshtml
@using Meetup2.Extentions_Custom
@model Meetup2.ViewModel.GroupViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
@if (Model.ShowButton)
{
    <div class="clearfix gap-bottom">

        @Html.ActionLink("Add a Meetup", "New", "Meetup", new { id = Model.Id }, new { @class = "btn btn-success pull-right" })


    </div>
}

<br />
<br />
<div class="clearfix gap-bottom">
    <div class="groupView">
        <img src="~/Content/Images/group1.jpg" alt="..." class="pull-left gap-right" height="242" width="200">

        <p class="text-justify">
            @Model.Description
        </p>
    </div>

</div>

<div class="page-header">
    <h4>Upcoming Meetups</h4>
</div>
<br />

<div ng-controller="appMeetupGroupCtrl">
  @foreach (var g in Model.MeetUp)
  {


    <div class="groupView-left">


        <h3>
            @Html.ActionLink(g.Title, "Show", "Meetup", new { id = g.Id }, null)
        </h3>
        <h4>
            <i class="fa fa-clock-o meetup-icon"></i>
            @g.DateTime.ToString("D")
            at
            @g.DateTime.ToString("h:mm tt")
            <br />
            <i class="fa fa-map-marker meetup-icon"></i>
            @g.Location

        </h4>
        <p class="text-justify">
            @g.Details

        </p>


    </div>
    <div class="groupView-right">


        @if (Model.ShowButton&& !g.IsCancled)
        {

            <span class="btn-group">

                <button type="button" class="btn btn-default">
                    <a href="@Url.Action("Edit", "MeetUp", new {id = g.Id}, null)">
                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                    </a>
                </button>
   <button 
                        class="btn btn-default"
                        mwl-confirm
                        title="Are you sure?"
                        message="Are you really <b>sure</b> you want to do this?"
                        confirm-text="Yes <i class='glyphicon glyphicon-ok'></i>"
                        cancel-text="No <i class='glyphicon glyphicon-remove'></i>"
                        placement="top"
                        on-confirm="CancleMeetup(@g.Id)"
                        on-cancel="cancelClicked = true"
                        confirm-button-type="danger"
                        cancel-button-type="default">
                     <i class="fa fa-remove" aria-hidden="true"></i>
               
                </button>

            </span>


            <br />
            <br />
        }


       
        @if (g.IsCancled)
        {
            <div class="label label-danger">
                Cancled &nbsp;
            </div>

        }

     

    </div>
    <br />
  }


</div>